# Tensorflow Basics
Here we will see 
    1. How to define basic matrices
    2. Create an interactive session
    3. Basic Matrix multiplication

In [1]:
# Helping libraries
import tensorflow as tf

In [2]:
constant = tf.constant(10)
fill_matrix = tf.fill((4, 4), 8)
my_zeros = tf.zeros((4, 4))
my_ones = tf.ones((4, 4))
my_random = tf.random_normal((4, 4), mean=0, stddev=1.0)
my_randomu = tf.random_uniform((4, 4), minval=0, maxval= 5)

all_in_one = [constant, fill_matrix, my_zeros, my_ones, my_random, my_randomu]

## Create an interactive session

In [3]:
sess = tf.InteractiveSession()

### Printing all the outputs once by one

In [4]:
for i in all_in_one:
    print(sess.run(i))
    print('\n')

10


[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.1964892   0.027832    1.0685886   1.3214697 ]
 [ 0.08595958  0.6432148  -1.3514285  -1.2243563 ]
 [ 0.00605912 -0.04036206  0.36944252  1.7487292 ]
 [ 1.4078075   0.98234     0.71645606 -0.9123325 ]]


[[0.21460414 1.4758658  2.7079864  3.1882775 ]
 [4.5753508  4.677349   0.7556021  2.108878  ]
 [1.5551198  1.5792769  1.3268131  2.5289755 ]
 [1.0284263  4.290866   2.0385373  0.2032888 ]]




### Once can also use eval instead of session

In [5]:
for i in all_in_one:
    print(i.eval())
    print('\n')

10


[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.21060014 -0.03322024 -2.2875502  -1.9398336 ]
 [-1.0039518   0.6778464   1.3607837  -0.3959595 ]
 [-0.57938826  0.39641848  0.6791731   1.3419064 ]
 [ 0.13460827 -0.1507616  -0.86617815 -0.48525748]]


[[0.040012   4.365739   0.3755349  0.09205699]
 [2.4878943  4.5105286  4.163065   2.9066467 ]
 [0.805099   3.0578709  1.2184238  3.4647322 ]
 [1.2857473  4.260679   0.7257384  0.01220465]]




## Matrix multiplication

In [6]:
mat_a = tf.constant([[1, 2],
                     [3, 4]])
mat_b = tf.constant([[2, 4],
                     [5, 5],
                     [2, 7]])

In [7]:
print(mat_a.get_shape())
print(mat_b.get_shape())

(2, 2)
(3, 2)


In [8]:
mat_mul = tf.matmul(mat_b, mat_a)

In [9]:
sess.run(mat_mul)

array([[14, 20],
       [20, 30],
       [23, 32]])